services:
  uploadhub_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filesdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - uploadhub_net

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      PUBLIC_MINIO_ENDPOINT: "http://localhost:9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - uploadhub_net

  uploadhub_web:
    build: ./app
    depends_on:
      - uploadhub_db
      - minio
    ports:
      - "8000:8000"
    environment:
      DB_HOST: uploadhub_db
      DB_NAME: filesdb
      DB_USER: postgres
      DB_PASS: postgres
      MINIO_STORAGE_ENDPOINT: "http://minio:9000"
      MINIO_STORAGE_ACCESS_KEY: "minioadmin"
      MINIO_STORAGE_SECRET_KEY: "minioadmin"
      MINIO_STORAGE_BUCKET_NAME: "uploads"
      PUBLIC_MINIO_ENDPOINT: "http://localhost:9000"
    networks:
      - uploadhub_net

volumes:
  db_data:
  minio_data:

networks:
  uploadhub_net:
    driver: bridge

